version: '2'
services:
  nginx-proxy:
    build:
      context: .
      dockerfile: Dockerfile
#    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "1337:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.local
